build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
    coverage:
      tests:
        override:
          #- command: mkdir -p build/logs && vendor/bin/phpunit --coverage-clover build/logs/clover.xml
          - command: mkdir -p build/logs && if ! php -m | grep -q 'xdebug'; then pecl install xdebug || true         echo "zend_extension=xdebug.so" >> "$(php -r 'echo php_ini_loaded_file();')" echo "xdebug.mode=coverage" >> "$(php -r 'echo php_ini_loaded_file();')" fi && php -m && php -i | grep xdebug.mode  # Verify Xdebug mode
            coverage:
              file: build/logs/clover.xml
              format: clover
            idle_timeout: 360
  environment:
    # Languages
    php:
        version: "8.2"
